getting-started/installation-guide.md

Cleanup unneeded steps in the setup process.
I got a bit aggressive previously when adding dependencies. Only repositories that are directly referenced from the systemlink or systemlink-admin chart are required. Indirect dependencies are pulled directly from the packaged charts. 
Validated on Rancher.

Remove unneeded repository configuration.

---

getting-started/installation-guide.md

Iterating on the install steps now that I can test with a nearly-final repository. Don't need to explicitly specify the NI repository on the command line and don't need to setup other repositories at all.
Simplifies install process.
Validated against Rancher.

Further Simplify install commands.

---

.vscode/settings.json
getting-started/installation-guide.md

Fix incorrect name of the admin chart.
Name is wrong.
Test deployment on Rancher.

Fix admin chart name.

---

getting-started/installation-guide.md
getting-started/templates/systemlink-values.yaml

- [x ] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/install-systemlink-enterprise/blob/master/CONTRIBUTING.md).
Updates the hostname for the helm repo to be `niedge01`
This hostname must be used for GM to successfully authenticate
Added the helm repo locally using GM's credentials and this hostname.

use niedge01

---

getting-started/installation-guide.md

Fix a typo in the Installation Guide
N/A

Fix typo in Installation Guide

---

getting-started/configure-authentication.md

Documents the OpenID Connect redirect URL
Without this users cannot fully configure the application instance in their OIDC provider 
None. It would be helpful if someone who has access to this configure in Azure AD for enterprise-dev could verify this URL. I don't have access to that application in AAD.

OIDC redirect

---

getting-started/installation-guide.md

Provides rational for the elevated cluster privileges needed to install the systemlinkadmin chart.
GM requires documented rational for providing users and pipelines elevated privileges.
GMs k8s admin provided the SLE administrators necessary privileges perform the initial install.

provide rational for admin privileges

---

getting-started/templates/systemlink-values.yaml

Update the dremio section to reflect the new name (`sldremio`). Add commented out values regarding resource requests with comments explaining their purpose.
Requested as part of Dremio work. Tracked by [Task 1948710](https://dev.azure.com/ni/DevCentral/_workitems/edit/1948710): Update GitHub template and cluster requirements documentation
N/A

Update dremio section

---

getting-started/templates/systemlink-values.yaml

Documents required nbexec worker configuration.
nbexec worker configuration was previously missing from the template. This adds it using the new properties added to the 0.2.0 version of the chart.
Verified new properties with internal pipelines.

Update nbexec worker configuration example

---

getting-started/templates/systemlink-secrets.yaml

There was a typo in the original chart. This replicates the fix in the template file. 
Will need this change once the fixed chart is published. 
-

Fix typo in secret name

---

getting-started/configure-authentication.md

Document the offline_access scope and path.
Customer's should be aware of this feature.
Linted and [tested](https://github.com/ni-kismet/helium-webserver/pull/1896)

Document the offline_access scope and path.

---

getting-started/templates/systemlink-values.yaml

Fixes [this bug](https://dev.azure.com/ni/DevCentral/_workitems/edit/1984692)
Without this change, Grafana deployments will be broken using the current template.
Chris and I found this on a call and verified that this new yml structure is correct.

Fix incorrect position of Grafana database config

---

.vscode/settings.json
getting-started/secrets.md
getting-started/templates/systemlink-secrets.yaml

Documents secrets for the user data service.
Secrets will be required once this service is running.
N/A

Document user data service secrets

---

getting-started/templates/systemlink-values.yaml

Updates `systemlink-values.yaml` with the recommended values for Dremio. These values will be the default for the DataFrame service.
The new values match [the spreadsheet](https://nio365-my.sharepoint.com/:x:/g/personal/mark_black_ni_com/ESnkTxz5qUtFrgcWjhiMILQBlLN9yq2_ss-Z7jrMmheHLA?e=ZbeDFu) with estimates for the resources required for cluster.
NA

Update systemlink-values for Dremio

---

.vscode/settings.json
getting-started/templates/systemlink-secrets.yaml

Name was changed in the Helm chart.
Need to match the Helm chart.
N/A

Update the name of the userdataservice to userdata

---

getting-started/templates/systemlink-values.yaml

This feature is ready to be enabled, and we have toggled it in the umbrella chart: https://dev.azure.com/ni/DevCentral/_git/Skyline/pullrequest/322773
This flag needs to be set to enable the Grafana RBAC integration.
n/a

Enable Grafana access control mirroring

---

getting-started/templates/systemlink-values.yaml

Highlights need to configure minio volume size when deploying SLE. 
Improve installation process. This is not a breaking change. 
N/A

Add minio volume size to template

---

getting-started/templates/systemlink-secrets.yaml

Adds new secrets to the secrets template.
A new routine management-related service will be added in the following releases. This service will require new secrets.
N/A

Add secrets for Routine management

---

getting-started/templates/systemlink-values.yaml

Update the getting started template to account for the new execution engine used for notebook execution.
Also nbexecworker is not longer shipped with SystemLink.
It reflects the current state of the product.
N/A

Update getting started template to account for Argo Workflows

---

release-notes/09-2022/SLE-SBOM-09-29-2022/blah.sh

The script I was using to rename files got submitted. Delete it
This file should not have been submitted.
N/A

Remove incorrectly submitted script

---

getting-started/configure-authentication.md
getting-started/configure-external-postgres.md
getting-started/configure-hostnames.md
getting-started/installation-guide.md
getting-started/mirroring.md
getting-started/secrets.md

Changes links from those on the staging server to official production link.s
No longer need to link to staging server
Tested links

update to production links

---

getting-started/templates/systemlink-values.yaml

Comment-out the Grafana plugin configuration values. These values are already set in the default values file and maintaining them here as well is only creating a maintenance burden for both developers and the customer. I will also update the release notes to mention this change.
Simplify developer and customer upgrade experience.
None - documentation

Comment-out Grafana plugin values

---

getting-started/templates/systemlink-values.yaml

This change was suggested by Melissa in a [previous PR](https://github.com/ni/install-systemlink-enterprise/pull/84), but I just realized I never actually pushed the change before submitting the PR.
Clarifies comments surrounding how to include additional Grafana plugins.
N/A - Only updating comments.

Clarify how to include additional Grafana plugins

---

getting-started/templates/systemlink-secrets.yaml
getting-started/templates/systemlink-values.yaml

Documents the secrets and values need to configure the notification and SMTP services
This documentation is needed for the next GM deployment
N/A

Documented the values and secrets for the notification and SMTP services

---

getting-started/templates/systemlink-secrets.yaml

Add new required secrets for the new `routinescheduletrigger` helm chart
Documenting new required values
N/A

Add routinescheduletrigger secrets

---

release-notes/2022-12/README.md

Updates `systemlink` helm chart to `0.9.88`.
A new version of the systemlink helm chart has been made available
N/A

Update systemlink helm chart version

---

release-notes/2022-12/README.md

Correct top level helm chart version
Correct top level helm chart version
NA

version bump

---

getting-started/templates/systemlink-secrets.yaml

Add license activation ID documentation to the secrets template.
This value will be required for future SLE customers.
N/A

Add activation ID documentation

---

getting-started/templates/systemlink-values.yaml

Include values regarding Dremio node selection.
This is valuable configuration for proper utilization of nodes and execution of Dremio.
Documentation change.

Dremio node selection values

---

getting-started/templates/systemlink-values.yaml

Adds global image registry override for DFS Kafka UI image.
GM will need this change for Kafka UI to work in their environment.
Trivial values file update.

DFS Kafka UI image registry configuration

---

getting-started/templates/systemlink-values.yaml

Add Kafka UI image pull secrets configuration.
Required for Kafka UI to work for GM.
Tested configurations locally with DFS via minikube.

Specify Kafka UI image pull secrets

---

getting-started/templates/systemlink-secrets.yaml
getting-started/templates/systemlink-values.yaml

Add more context to dashboards YAML comments:
- DB user permissions
- Admin credentials limitation
- Helps avoid common pitfalls when deploying SLE
n/a

Dashboards documentation improvements

---

release-notes/2023-03/README.md

Adds link to bug fix list
There was a TODO in the release notes!
NA

bug fix list link

---

release-notes/2023-03/README.md

Fixed version of DFS. Added version of Kafka UI
Correct errors and omissions from release notes
Manual review of versions in the bundle on edge node

2023 03 versions

---

release-notes/2023-03/README.md

Includes strimzi dependencies under 3rd party containers. They were listed in the sbom but not release notes.
More accurate release notes.
Verified against SBOM list.

Include Strimzi dependencies

---

getting-started/templates/systemlink-values.yaml

Documents new toggle.
This will allow GM to not deploy a service they are not using.
Testing with helm tempalte.

Document the minio deployment toggle

---

release-notes/2023-04/README.md

- Updates the wording for helm breaking changes
- Add behavior changes
Required for release notes
NA

2023 04 behavior changes

---

getting-started/templates/systemlink-values.yaml

Adds user telemetry configuration to the template Helm chart.
Users need to make a decision about enabling telemetry at install time.
N/A

Add user telemetry settings to values file template

---

getting-started/templates/systemlink-secrets.yaml

The next release of SystemLink Enterprise will add support for tags. This PR adds the required minimum values that have to be set for a successful deployment/upgrade of SLE.
Adds required documentation.
Internal testing on k8s clusters.

Add tags.secrets to systemlink-secrets template

---

getting-started/templates/systemlink-secrets.yaml

The secret configuration was incorrectly defined in the template file.
Need a correct definition so that users can define the secret.
Deployment testing.

Fix activation ids secret

---

chapter-template/release-notes-template.md

Add RabbitMQ version support information to the release notes template.
This information should be communicated to the user before they try upgrading their deployment. 
N/A

Add RabbitMQ version table to the release notes template

---

getting-started/templates/systemlink-values.yaml

Document webserver ingress configuration regarding the read timeout
This is related to this: https://ni.visualstudio.com/DevCentral/_git/Skyline/pullrequest/530848?_a=files
The change is already submitted & validated in the product

Document webserver ingress configuration regarding the read timeout

---

getting-started/templates/systemlink-secrets.yaml

Document secrets needed for repository service

Add secrets for package repository

---

getting-started/templates/systemlink-secrets.yaml
getting-started/templates/systemlink-values.yaml

The next release of SystemLink Enterprise will add support for comments. This PR adds the required minimum values that have to be set for a successful deployment/upgrade of SLE.
Adds required documentation.
Internal testing on k8s clusters.

Add Environment Configuration Values and Secrets of Comments Service

---

chapter-template/release-notes-template.md

Update the release notes template to remove the redundant reference found in #162. Specifically [this comment](https://github.com/ni/install-systemlink-enterprise/pull/162#discussion_r1328941052).
Release notes created from this template will not have the redundant reference.
NA

Update release notes template

---

release-notes/2023-10/How-to-reset-Dremio.md
release-notes/2023-10/Perform-a-hard-reset-on-the-redis-cluster.md
release-notes/2023-10/README.md
release-notes/2023-10/Remove-Kafka-from-the-cluster.md

Makes changes to structure and wording. There should be no material changes to the content.
Accelerate the PR in `see-release-notes-2023-10` branch.
NA

2023 10 release note mblack refactor

---

chapter-template/release-notes-template.md
release-notes/2023-11/README.md

Provides my edits to the 2023-11 release notes
Cleans up some wording and improves style and grammar.
NA

mblack edits

---

getting-started/templates/systemlink-secrets.yaml
getting-started/templates/systemlink-values.yaml

The license service is being removed from the product for now. Removing the associated settings from the Helm templates.
Reduce user confusion around a removed service.
N/A

Remove license service from the Helm templates

---

release-notes/2024-01/README.md

Include a reference to dark mode support in new features.
Important new feature that shouldn't be missed.
NA

reference dark mode

---

getting-started/templates/systemlink-secrets.yaml
getting-started/templates/systemlink-values.yaml

The next release of SystemLink Enterprise will add support for work orders optionally. This PR adds the required minimum values that have to be set for a successful deployment/upgrade of SLE.
Adds required documentation.
Internal testing on k8s clusters.

Add Secrets and Values of Work Order Service

---

getting-started/templates/systemlink-secrets.yaml

Added new values to match the file ingestion values in this PR:
https://dev.azure.com/ni/DevCentral/_git/Skyline/pullrequest/636975
After the new changes will be pushed, we can enable a new route that will let us download a file using a token

Add new secrets and values to file ingestion in the template

---

getting-started/templates/systemlink-secrets.yaml

PR on ni.com documentation -> https://dev.azure.com/ni/Users/_git/Documentation%20Reviews/pullrequest/660179
Document systems state service secrets

Document systems state service secrets

---

getting-started/templates/systemlink-secrets.yaml

Improve doc for salt-master

---

getting-started/templates/systemlink-secrets.yaml
getting-started/templates/systemlink-values.yaml

Update helm starter template to accommodate for newly added feedservice
Feed it's a new service added to SystemLink
Values validated with NI internal cluster

Add feeds to helm starter template

---

getting-started/templates/systemlink-secrets.yaml
getting-started/templates/systemlink-values.yaml

This reverts commit f1565a94c8d44ac433dea5e3f084643df9a97806.
Temporarily revert secret change for the current release.
Template is broken with the current release Helm chart.
N/A

Revert "Remove references to generic artifacts (#189)"

---

getting-started/templates/systemlink-values.yaml

Update the values template with more details related to the configuration of custom CA certificates.
Necessary documentation.
N/A

Add CA certificate configuration details to template

---

getting-started/templates/node-selectors.yaml

Adds node tolerations for notebook execution pods.
Keep consistency with other areas in SystemLink.
Internal

Add tolerations for notebook execution

---

getting-started/templates/systemlink-values.yaml

Add notebook execution resource profile to the starter template.
Resource profiles will be referenced from the public documentation, so we need to have them defined here.
Internal.

Add notebook execution resource profiles to the starter template

---

getting-started/templates/sizing-examples/README.md

Adding a READMe to clarify how to use the contents of the sizing examples folder.
Documentation
N/A

README for the sizing examples folder

---

getting-started/templates/sizing-examples/systems-sizing-example.yaml

This is part of our effort to improve documentation around configuring the SLE application for deployment. This document was previously reviewed as part of an AzDO PR and is being moved to github.
Documentation.
N/A

Check in sizing example for the Systems and Asset Management workflow

---

getting-started/templates/sizing-examples/core-sizing-example.yaml

This is part of our effort to improve documentation around configuring the SLE application for deployment. This document was previously reviewed as part of an AzDO PR and is being moved to github.
Documentation.
N/A

Check in sizing example for the Core workflows

---

getting-started/templates/AWS/aws_supplemental_values.yml
getting-started/templates/Azure/azure-supplemental-values.yaml

-[x ] This contribution adheres to
Updates supplemental values files to use the new DFS health check route.
This change will be required for successful deployments starting with the July release. 
N/A

Update DFS health check configuration
