ni/install-systemlink-enterprise

getting-started/installation-guide.md
I discovered yesterday that a test from the third-party Grafana Helm chart is not cleaning up automatically. Until we can upstream a fix for this issue, documenting steps to clean up the test manually.
Also added some text to inform the user that the test command runs silently for several minutes. It's easy to think that it has hung.
Failing to cleanup the test pod could cause issues with autoscaling of Grafana containers.
Verified on Rancher.
=> Add cleanup instructions for the Grfana Helm test.

getting-started/installation-guide.md
The Grafana test issue was fixed today. Removing the extra cleanup step.
Removes unnecessary step.
I'm waiting on pipeline runs to verify this fix. Will verify before committing.
=> Remove cleanup step for Grafana test

getting-started/templates/systemlink-values.yaml
Current defaults in the test monitor package are too small for release usage. Increase usage in the values template.
Works around bad pod behavior due to insufficient resource allocation.
Verified on Rancher.
=> Temporarily adjust TestMonitor service resources.

getting-started/secrets.md, getting-started/templates/systemlink-secrets.yaml
These changes address the need to add the Session Manager services (nisession) to the lists of Whitelisted API Keys in both secrets.md and systemlink-secrets.yaml.  These changes are tracked by [Task 1946372](https://ni.visualstudio.com/DevCentral/_workitems/edit/1946372)
It's needed for service operation.
N/A
=> Add nisession Whitelisted API Keys

getting-started/secrets.md, getting-started/templates/systemlink-secrets.yaml, getting-started/templates/systemlink-values.yaml
Document the changes introduced in [this PR](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullrequest/301581). Installing our custom Grafana plugins requires hosting some .zip file artifacts, so we needed to add the concept of a generic artifact repo. In practice, this will be same as the Artifactory instance used for Docker images, but requires a new secret due to the limitations of the image pull secret.
This will be required for successful deployment of Grafana.
N/A
=> Document generic artifact secret

getting-started/templates/systemlink-values.yaml
Fixes an error deploying SLE using the `systemlink-values.yaml` template in this repo:
```
Error: template: systemlink/charts/dashboardhost/charts/grafana/templates/deployment.yaml:36:28: executing "systemlink/charts/dashboardhost/charts/grafana/templates/deployment.
yaml" at <include (print $.Template.BasePath "/configmap.yaml") .>: error calling include: template: systemlink/charts/dashboardhost/charts/grafana/templates/configmap.yaml:19:
33: executing "systemlink/charts/dashboardhost/charts/grafana/templates/configmap.yaml" at <$value>: range can't iterate over allow_loading_unsigned_plugins:"ni-slnotebook-data
source"
```
A space required by the yaml spec was missing, adding it fixes the error.
To enable successful deployment
Error is resolved w/ this fix.
=> Fix `range can't iterate over allow_loading_unsigned_plugins` error

getting-started/templates/systemlink-values.yaml
This reverts commit ba788b612840d52d1ecc915d53c5188a70963c42.
Reverts temporary change to override test monitor defaults
No longer needed in the next release. Should use the chart defaults. 
N/A
=> Revert "Temporarily adjust TestMonitor service resources. (#25)"

getting-started/configure-authentication.md
Once the create administrator job is moved into a separate Helm chart from the SLE chart, the way we reference the admin mapping values will change. This PR documents those changes.
Updates documentation around the initial admin mapping.
Once the SLE Helm chart pulls in the new admin creation Helm chart, current top-level values.yaml files will be wrong. This documents the change.
N/A
=> Updated create administrator value references

getting-started/templates/systemlink-values.yaml
Users might want to customize how many files can be uploaded by a single user over a period of one second. This limit applies per replica (currently there are between 2 and 10 replicas by default).
Example use-cases could be the ability to (temporarily) migrate large amounts of data, or permanently allowing users to upload a lot of files from the frontend.
Expose the `fileingestion.rateLimits.upload` value. 
Expose this value so that it can be changed on-demand
N/A
=> Expose fileingestion.rateLimits.upload value

getting-started/secrets.md, getting-started/templates/systemlink-secrets.yaml
Adds documentation and an entry for the whitelisted API key for the dashboard host service (Grafana).
This will be necessary for implementing RBAC control in Grafana.
N/A
=> Add dashboardhost whitelisted API key

getting-started/templates/systemlink-values.yaml
I want to ensure we consistently use niedge01 by default.
Fixes default.
N/A
=> Uncomment global registry override

getting-started/templates/systemlink-values.yaml
This feature is not yet supported and needs to be explicitly toggled off.
Disables incomplete feature.
Test deployment.
=> Disable dashboardhost RBAC support by default for now.

getting-started/templates/systemlink-values.yaml
The default nginx upload limit is around 2Mb. Increase the default for services that support file uploads.
Fixes issues with upload sizes being limited.
Test deployment.
=> Override upload limit defaults for services that support uploads

getting-started/templates/systemlink-values.yaml
#42 documented a change in how we install our custom plugins for Grafana, but the plugin URL in the values template wasn't updated to reflect this.
Necessary to install Grafana successfully.
n/a
=> Install Grafana plugin using correct URL

getting-started/templates/systemlink-secrets.yaml
I added a way to set the image registry for the image pull secret without requiring the global registry. Add that value to our templates.
Really just for completeness. Our configuration here uses the global registry.
Tested various dry run deployment scenarios.
=> Add new registry value for the image pull secret configuration

getting-started/templates/systemlink-values.yaml
We have a bug [here](https://dev.azure.com/ni/DevCentral/_workitems/edit/1954334) stating that the installation guide needs to provide better instructions if the customer is using their own S3 or MinIO instance, rather than the MinIO instance deployed with SLE by default. To make this more clear, I added `<ATTENTION>` blocks to the places where we reference the MinIO deployment's port number, stating that the port will need to be changed if the user is using a different S3 or MinIO instance.
I think a more complete fix requires a change to the installation guide, as it should call out what needs to be done if the user is not using the SLE-provided MinIO instance. I'll work with @MelissaHilliard on this, as the guide no longer lives in our GitHub repo.
None.
=> Clarify that s3.port must be configured if not using the SLE MinIO

getting-started/templates/systemlink-values.yaml
Override nginx request size limit for the dataframeservice, to allow for posting larger chunks of data at a time. 
The default nginx limit is very small, so we want it increased by default. This is similar to what was done for services that support file uploads [here](https://github.com/ni/install-systemlink-enterprise/pull/57).
Using the same increased limit on rancher currently (see [this PR](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullrequest/321330))
=> Add ingress annotation for request limit for dataframeservice

getting-started/templates/systemlink-secrets.yaml, getting-started/templates/systemlink-values.yaml
Per the Dremio [docs](https://raw.githubusercontent.com/dremio/dremio-cloud-tools/master/charts/dremio_v2/docs/setup/Important-Setup-Considerations.md#:~:text=*%20%60distStorage.type%60%3A%20By%20default%2C%20the%20%60distStorage.type%60%20is%20set%20to%20%60local%60.%20This%20**must**%20be%20changed%20prior%20to%20production%20use.%20We%20do%20not%20recommend%20users%20use%20local%20distributed%20storage%20as%20part%20of%20a%20production%20setup.), distributed storage must be configured in production deployments of Dremio, as it greatly increases performance. This change reminds customers to configure it, attempts to guide them, and offers pointers for connecting to MinIO. I also plan to work with @MelissaHilliard on some installation guide updates related to this change.
This makes it …
=> Add Dremio distributed storage configuration to systemlink-values.yaml

getting-started/templates/systemlink-secrets.yaml
Nbexecworker apikey was removed and instead nbexec-argo-wrofklow apikey was added.
=> Change nbexecworker to nbexec-argo-workflow in whitelisted api keys

getting-started/templates/systemlink-admin-values.yaml
Add example values that allow for configuring the Kafka operator Java heap size.
This configuration might be required for customers that make heavy use of Kafka.
This configuration was tested as part of the following change.
https://ni.visualstudio.com/DevCentral/_git/Skyline/pullrequest/360943
=> Add values for configuring Kafka operator Java heap size

getting-started/templates/systemlink-values.yaml
Improves the description of the insecure flag
Customer has complained the documentation is not clear enough
N/A
=> Improve documentation for insecure flag in nbexecservice s3 configuration

getting-started/templates/systemlink-values.yaml
In a call with Matt and Brad, we found that the documentation for Dremio's S3 endpoint configuration was lacking. Specifically, we couldn't remember if the config was meant to include the port or not.
This improves the documentation in our customer-facing values file.
We tested this while deploying SLE to Brad's internal cluster.
=> Clarify that the Dremio S3 endpoint config must include the port

getting-started/templates/systemlink-values.yaml
It isn't intuitive that Grafana's database must be created manually ahead of time. We've been bit by this a few times, so we should document it. While I have this file open, I'm also updating the example URL for Dremio's distributed storage configuration. I realized that dots are used to separate the FQDN segments, and not dashes.
This improves the documentation in our customer-facing values file.
We've tested this configuration internally.
=> Clarify that the Grafana db must be created manually. Clarify distStorage URL

getting-started/templates/systemlink-secrets.yaml, getting-started/templates/systemlink-values.yaml
We recently renamed the License Service Pods, Secrets, and other Helm value and need to update the customer facing getting started templates.  These will need to be configured by the end-user at the time of SLE installation once the License Service is added back to the Umbrella Helm chart.
The PRs to rename the License Service Helm resources have already gone in.  When the PR to add the License Service back to the Umbrella Helm chart goes in, we want the customer facing templates to match the actual values.
None for this PR.  The Helm resource rename was successfully deployed to [Main-Dev](https://ni.visualstudio.com/DevCentral/_build/results?buildId=3518588&view=results).  Main-Test had a failure due to the Terraform values not getting deployed and I'll work with Neil Stoddard to fix …
=> Rename License Service template values

getting-started/templates/systemlink-secrets.yaml
The existing URL doesn't work out of the box. Adding the "artifactory" segement fixes this issue.
Fixes broken URL.
This was validated with the September release on the customer success Rancher cluster.
More info can be found [here](https://ni.visualstudio.com/DevCentral/_workitems/edit/2205091).
=> Add "artifactory" segment to Grafana genericArtifactPull url

getting-started/templates/systemlink-values.yaml
Adds global telemetry configuration section to systemlink-values.yaml.
These configurations are now required to enable metrics collection for both OpenTelemetry and Prometheus. As far as I'm aware we currently only have OpenTelmetry metrics for Test Monitor and DFS (both in active development), but this also turns on/off Prometheus scraping for Kafka and KafkaConnect now.
Trivial values changes - tested on Stratus clusters.
=> Add global telemetry configuration section

getting-started/templates/systemlink-values.yaml
Include the OIDC enableUserInfo value.
We should document this value.
The web server was tested to support the user-info end-point.
=> Include the enableUserInfo value.

getting-started/templates/systemlink-values.yaml
Documents the `global.telemetry.includeUserInfo` Helm value.
This configuration is useful for non-repudiation, but is a potential security concern so is put behind a toggle that defaults to false.
Documentation change.
=> Document global.telemetry.includeUserInfo value

getting-started/templates/systemlink-values.yaml
RabbitMQ clusters in k8s have a known issue where the cluster can fail to restart after an unexpected shutdown. We are seeing this at customer sites. Adding documentation to our template on the recommended workaround for this issue.
Will help customers who encounter this issue in the future.
N/A
=> Add instructions for recovery after unexpected RabbitMQ shutdown

getting-started/templates/systemlink-secrets.yaml
Keys used by Elixir services expect the value stored in the Helm chart will be base64 encoded. Making sure this is explicitly documented. 
We had internal deployments that had failed to format keys correctly because this requirement was not clear in the documentation. Trying to prevent that happening to users.
N/A
=> Clarify encoding requirements for encryption keys

getting-started/templates/systemlink-values.yaml
Remove the kafka-ui image registry override configuration.
These values are no longer needed as the new version of the kafka-ui chart supports global image registry.
Trivial values file updates.
=> Remove kafka-ui image registry override value

getting-started/templates/systemlink-values.yaml
1. Add the ingress options that we use on rancher, to reflect that in order to upload large files, you need to turn off the proxy request buffering
2. Document the `uploadLimitGB` field
Better documentation for file uploads for clients
N/A
=> Update fileingestion values to reflect large files upload

getting-started/templates/systemlink-values.yaml
Includes and example for configuring rate limits for Dataframe service with the default values.
This gives an example to costumers on how to configure the concurrent requests handled by each of the replicas of the Dataframe service.
Testing with helm template
=> Added example for configuring Dataframe service rate limits

release-notes/2023-01/README.md
I previously grabbed the versions from the helm charts themselves which do not include the patch versions, this PR adds the patch versions of the helm charts in the latest release bundle.
Documentation change, no testing required.
=> Add patch versions of helm charts to release notes.

getting-started/templates/systemlink-values.yaml
The `sl-jupyterhub` 1.0.0 helm chart brings a breaking change, as Jupyter usernames will be based on user emails instead of user emails. Clients can opt-out of this by setting the JUPYTER_USERNAME_AS_SYSTEMLINK_USER_ID helm value to "true", to use the legacy implementation.
Also, the resource allocation for user pods changed. Specifying the defaults here such that, if clients wish to have more or less, they can easily find where to change it.
The helm values are displayed in the template for easier modification.
This values have been tested on our dev and test environments.
=> Add new sl-jupyterhub default helm values

getting-started/templates/systemlink-values.yaml
Includes the default value for appendable table limit and description to help the user tune their deployment.
This is a configuration option added for the 2023-04 release of the Dataframe service. This PR describes the new configuration and points to a [knowledge base article about it](ni.com/r/setendofdata)
`helm template`
=> Added appendableTableLimit configuration for Dataframe service

getting-started/templates/systemlink-values.yaml
Updated 2023-06 breaking changes for release notes [here](https://nio365.sharepoint.com/:x:/r/sites/ASWSystemLink/Shared%20Documents/SLE%20Development/Helm%20Chart%20Breaking%20Changes,%20Software%20Behavior%20Changes%20for%20the%20Release%20Notes%20-%20out%20of%20May%202023%20(SLE%202023-06).xlsx?d=w8144df90bcf644ef8aacda6e44615d76&csf=1&web=1&e=HWacZM).
Add the new apiIngress section to the dashboardhost values.
Also cleaned up and removed properties that we don't expect the user to change here from the main ingress.
We need to expose Grafana's API on the API Ingress in order to address [Bug 2373035](https://dev.azure.com/ni/DevCentral/_workitems/edit/2373035): [Prod] The dashboard app appears in the navigation tree on prod
`helm template`
=> Add dashboardhost apiIngress for Grafana

getting-started/templates/systemlink-secrets.yaml, release-notes/2023-07/NewSaltMaster-SystemsMigration.ipynb, release-notes/2023-07/SystemsConnectionMigration.md
This release is coming with a breaking change. All the connected client systems will be disconnected after the upgrade because we've switched to the new salt-master implementation. We are not providing an automated migration process within the product, we are providing manual steps.
I've also created a PR for the ni.com public documentation-> https://ni.visualstudio.com/DefaultCollection/Users/_git/Documentation%20Reviews/pullrequest/510237
We need to document the migration process in an accessible location for the Customer Success team.
The migration steps have been executed with success against dev/test/rancher.
=> Add documentation for migrating systems for the 2023-07 release

getting-started/templates/systemlink-values.yaml
In a [PR comment](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullRequest/523128#1689686266), we determined that we were unnecessarily duplicating some of Grafana's autoscaler config in this file.
I left the bit about enabling or disabling the autoscaler based on whether or not the user is connecting Grafana to an external database, as I think that's important enough to surface here.
Removes unnecessary configuration, keeping the `systemlink-values.yaml` file smaller.
I verified that the values that we're removing are identical to the defaults specified in the Grafana chart [here](https://dev.azure.com/ni/DevCentral/_git/Skyline?path=/Grafana/helm/values.yaml&version=GBusers/pvallone/audit-checklist-tracing&line=203&lineEnd=216&lineStartColumn=1&lineEndColumn=37&lineStyle=plain&_a=con …
=> Remove unnecessary autoscaler config for Grafana

getting-started/templates/systemlink-secrets.yaml
Document `TagHistorian` required secrets as it will be deployed soon.
Add `taghistorian` and its secrets to the `getting started` template.
Document `TagHisotrian` required secrets.
=> Add taghistorian secrets

.yamllint, release-notes/2023-10/MongoDB_Migration/Chart.yaml, release-notes/2023-10/MongoDB_Migration/README.md, release-notes/2023-10/MongoDB_Migration/templates/configmap.yaml, release-notes/2023-10/MongoDB_Migration/templates/job.yaml, release-notes/2023-10/MongoDB_Migration/values.yaml
Adds a README.md and Helm Chart to assist customers with migration of documents to a single instance of MongoDB.
Customers need more information to help them with this migration.
The contents are based off of the Skyline/Terraform/stratus_backup/helm/mongodb_merge chart used to migrate the main-dev environment.
=> MongoDB Migration release notes for 2023-10

getting-started/templates/systemlink-secrets.yaml, getting-started/templates/systemlink-values.yaml
Adds the `global.mongodb` section to the getting started templates values file
The default for MongoDB connection to and external instance is changing in the October release. We need to update documentation/getting started-type guides.
Stratus main-dev is running on MongoDB Atlas.
=> Add global.mongodb section

getting-started/templates/systemlink-values.yaml
Make the new SMTP message limit settings user-facing.
Document new settings with potential breaking behavior. This settings are not supported in the November release so these changes should wait until after that release is completed.
N/A
=> Add SMTP message limits to values template

getting-started/templates/systemlink-secrets.yaml, getting-started/templates/systemlink-values.yaml
Adding the new values that were added in this PR: https://dev.azure.com/ni/DevCentral/_git/Skyline/pullrequest/589182?_a=files&path=/TestMonitorService/helm/values.yaml to the getting started template with documentation.
So that users are aware of the new option of using a separate postgres user for schema migrations.
The helm changes have been tested, this is just updating our template to include the new values.
=> Add values to getting started template for postgres migration user.

getting-started/templates/systemlink-admin-values.yaml, getting-started/templates/systemlink-values.yaml
Removes YAML values related to the Kafka operator and DFS Kafka configuration.
The 1.0.0 DFS helm chart removes support for Kafka-based data table ingestion. The 0.20.4 admin chart also removes the Kafka operator. So these values are no longer referenced by anything and should be removed.
Ran a `helm template` command for the latest admin chart using the updated template (with some values filled in for secrets).
=> Remove values related to Kafka

getting-started/templates/systemlink-values.yaml
We added a new OIDC configuration parameter as part of supporting ForgeRock as an IdP. This is not a breaking change as the default value gives the same behavior we had previously. We've chosen a safe default because there are known issues with enabling the new behavior with Azure AD, but the new behavior is recommended by the OIDC spec and so we want to document the option and recommend that users enable it if their infrastructure supports it. 
This change applies to the January 2024 release. 
Documenting a setting in the template. 
TODO: Detail what testing has been done to ensure this submission meets requirements.
=> Document the webserver.oidc.enableLogoutToken value

getting-started/templates/systemlink-secrets.yaml, getting-started/templates/systemlink-values.yaml
Updates the values.yaml and secrets.yaml templates for Specification Management service which can be configured by the customers.
Customer installing the Specification Management service as part of SystemLink Enterprise can configure the values and secrets if required.
NA
=> Add values and secrets of Specification management service

getting-started/templates/systemlink-secrets.yaml
Document the need of an `encryptionKey` for the Systems State service in order to have state content encrypted.
Have documentation for the encryption key needed to have state content encrypted.
The Helm value has been tested on the NI clusters.
=> Document encryption key for Systems State Service

getting-started/templates/systemlink-values.yaml
Reverting 6cf9f01e496b6ec4de0d390082a9cb7ebfaba684, as Bitnami [fixed](https://github.com/bitnami/charts/issues/23953#issuecomment-2011373609) the issue that caused us to want to hide the port configuration. We shouldn't have deleted the anchor declaration anyway -- probably we should have just added an "ATTENTION" callout stating that it should not be changed.
See above.
Reverting to a known-good configuration.
=> Revert "Remove MinIO containerPort config (#188)"

getting-started/templates/systemlink-secrets.yaml, getting-started/templates/systemlink-values.yaml
This reverts commit a8b9fa57353de4fad92902da1b893e0297f18f1f.
The issue that caused this change to be initially reverted has been fixed.
The issue that caused this change to be initially reverted has been fixed.
Top-level Helm chart was built with secret removed.
=> Revert "Revert "Remove references to generic artifacts (#189)" (#196)"

getting-started/templates/systemlink-values.yaml
Expose options to specify trusted certificates in systemlink. 
Custom certificates support was added for s3 communication.
Tested on NI internal cluster.
=> Expose trusted certificates support in helm starter template

getting-started/templates/systemlink-values.yaml
Enabling the work order service by default as the Landing page shows Test Plans and it should be reachable when clicked on it.
Adds required documentation.
Internal testing.
=> Enable Work Order Service by default

getting-started/templates/systemlink-secrets.yaml, getting-started/templates/systemlink-values.yaml
- Add placeholder secret config for required secrets.
- Highlight rate limiting config in the top-level values file, for discoverability. We do this for the rate limiting config of other services too.
- Highlight inactive alarm retention config in the top-level values file. Users may want to configure how long inactive alarms remain in the database.
We've added the Alarm Service to the top-level chart, for inclusion in the `2024-06` release, so we should have attention callouts for its required secret config. We typically expose rate limiting config in the top-level values file as well.
None
=> Add placeholder secret config for the Alarm Service

getting-started/templates/systemlink-values.yaml
Update starter-template values for notebook execution
The new helm charts comes with a different ttl strategy, where secondsAfterCompletion is being set to avoid workflows in error state not being cleaned up.
Also those setttings are mentioned in public doc: https://www.ni.com/docs/en-US/bundle/systemlink-enterprise/page/configuring-the-notebook-exectution-service.html
Tested in internal clusters.
=> Remove ttlStrategy from systemlink starter template

getting-started/templates/AWS/aws_supplemental_values.yml
Adds an initial AWS supplemental values file. Customers can pass this file in addition to their other systemlink-values.yml file to set AWS-specific values for the services.
Initially I am tackling two "sets" of supplemental values:
- Setting AWS ALB ingress annotations. Used in conjunction with the suggested Application Load Balancer Controller. Without these AWS Target Groups will not be healthy and allow traffic through.
- saltmaster NLB Target Group ARNs
There are likely other values we would want to inform customers about related to AWS-hosted environments. This is a start.
It's the right thing to do.
Currently having a customer use this for their new AWS-based environment deployment.
=> Initial AWS Supplemental Values File

getting-started/templates/systemlink-values.yaml
Document the httpProxy configuration for FeedService and Repository Service
We need to explicitly document this for SLE deployments that don't have direct access to internet, so the networking implies using a proxy.
Manually edited helm values and have done multiple deployments to make sure the configs are propagated as expected in the applications
=> Add proxy configs for Repository & Feed services

getting-started/templates/systemlink-values.yaml
Since [S3 buckets are added](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullrequest/771882?_a=files) for nbexecution service, and its [added as mandatory helm variables](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullrequest/769716?_a=files). This PR is adding this new breaking change in getting started.
Adding a new breaking change made in NbExec helm.
NA
=> NbExec | Add S3 configurations to helm

getting-started/templates/systemlink-values.yaml
Bitnami updated their documentation around how to configure their chart to keep a RabbitMQ deployment healthy. I'm updating our user-facing documentation to reflect the latest recommendations.
Updating docs.
N/A
=> Cleanup RabbitMQ recovery documentation

getting-started/templates/Azure/azure_supplemental_values
This PR add the supplemental values file for azure app gateway ingress and service health paths
Provide customers with the ingress and health check annotations template to speed up deployment of environments in Azure.
Deployed an Azure environment manually using this supplemental values file and verified that the services start correctly with successful health checks.
=> Initial commit of azure supplemental values file

getting-started/templates/systemlink-values.yaml
The Alarm Service now enforces limits on the number of alarms that can be created. We've also added a facility to automatically delete active alarms that haven't been updated in a configurable number of days. This PR exposes this configuration in the user-facing values file.
From talking to @prestwick, we think it makes sense to expose the alarm limit and retention configuration in the user-facing values file, as it's something users may want to adjust. We're also going to point to this configuration from our public docs.
I verified the nesting matches what we have in the service's values file.
=> Expose alarm limit configuration in the user-facing values file

getting-started/templates/pilot-sizing.yaml
Provide a sizing file that specifies resources and replicas for a SystemLink Enterprise pilot deployment.
This pull request adds a new template yaml file that specifies the resources and replica counts for a pilot-sized deployment.
Provide customers with a template to speed up initial deployment of pilot environments.
Deployed the solution manually and verified that the services start correctly and are capable of handling a reasonable load for a pilot.
=> Sizing yaml template for SystemLink Enterprise pilots

getting-started/templates/node-selectors.yaml, getting-started/templates/systemlink-values.yaml
Allow the customization of the deployment using node selectors, tolerations, and affinities.
This PR creates a configuration yaml file that can be supplied as a --values argument to the helm installation command to customize the deployment's node selectors, tolerations, and affinities.
Provide flexible configurations for different deployment topologies.
I have deployed this to an internal testing environment to ensure that pods respect the node selectors and taints.
=> Add node selectors config file

getting-started/templates/node-selectors.yaml
Ensure notebook execution pods are scheduled on the labeled node.
Corrects a missing node selector for notebook executions using argo workflows.
This ensures that notebook workloads are scheduled on the correctly labeled node.
Visual inspection of helm charts.
=> Add node selector for nbexecservice argo workflows

getting-started/templates/systemlink-admin-values.yaml, getting-started/templates/systemlink-values.yaml
Add details about argo workflows instance id and crds installation, needed when there is an already installed argo-workflows in the cluster
These are already defined in public doc: https://www.ni.com/docs/en-US/bundle/systemlink-enterprise/page/configuring-the-notebook-exectution-service.html
My understanding is that the public doc should reference configuration in the helm values, so it's better to have the configuration commented there.
N/A, just placing what is already documented.
=> Add missing details about argo workflows instance id

getting-started/templates/pilot-sizing.yaml, getting-started/templates/systemlink-secrets.yaml, getting-started/templates/systemlink-values.yaml
Add dynamic form fields (DFF) sizing.
This duplicates the values added to the SLE release.
Merge should be done, after the internal merge is completed
N/A
=> Update pilot-sizing.yaml with adding DFF

getting-started/templates/pilot-sizing.yaml, getting-started/templates/systemlink-values.yaml
Adds a modest Iceberg engine for pilot deployments.
To isolate reads from writes at runtime, and to provide Dremio with enough resources to compact and add data to tables of modest size, we need to provision an Iceberg execution engine. We also need to adjust the number of concurrent compaction and ingestion jobs we ask Dremio to handle so that we don't overwhelm the modest Iceberg engine we're deploying for pilots.
We shouldn't merge this until we're ready to enable compaction by default.
I verified this Iceberg engine can handle a burst of 30 concurrent reference table writers. That is, 30 threads writing 200k rows to a different table with 200 FLOAT64 columns in 4k batches. All data was compacted and made available for query within 10 minutes of ingestion starting.
=> DFS: Update pilot config for the compaction feature

getting-started/templates/systemlink-secrets.yaml, getting-started/templates/systemlink-values.yaml
Adds documentation for the DFS Nessie bearer token.
The secret is now required and users must specify a value.
PR
=> Add nessie credential secret to values template

getting-started/templates/systemlink-values.yaml
- [x ] This contribution adheres to
A new storage setting is introduced under feedservice. It has a type property that specifies the storge service to use.
The s3 settings under feedservice are moved under storage.s3
Document changes in existing settings.
=> Add storage to feedservice, move s3 under storage

getting-started/templates/pilot-sizing.yaml
The default rate limit for the web server assumes a minimum deployment of 4 pods. The pilot config only deploys 2 pods. I'm concerned that particularly busy pages in the UI could start seeing 429 errors with this sizing. Increasing the rate limit should avoid this.
Tweak pilot configuration file.
N/A
=> Update WebServer rate limit in the pilot config

getting-started/templates/systemlink-values.yaml
See #248. The DataFrame Service has made the same change to Helm values where `dataframeservice.storage.s3` should be set instead of `dataframeservice.s3`, which is deprecated. No change to the values themselves, only indenting an extra level and adding `storage.type`.
Document change in values to set.
None
=> Add storage to dataframeservice, move s3 under storage

getting-started/templates/systemlink-values.yaml
A new storage setting is introduced under our services (file ingestion service, feeds, DFS) . It has a type property that specifies the storge service to use.
The s3 settings under NbExecService are moved under storage.s3
Document changes in existing settings.
N/A
=> Add storage to NbExecService, move s3 under storage

getting-started/templates/systemlink-values.yaml
- A new storage setting is introduced under fileingestion. It has a type property that specifies the storage service to use.
- The s3 settings under fileingestion moved under storage.s3.
Document changes in existing settings.
=> [FileIngestion Service] Move the s3 config under storage

getting-started/templates/systemlink-secrets.yaml, release-notes/2025-04/README.md
Documenting missing information about new required tageventprocessor-apikey secret.
Ensures that users that upgrade to 2025-04 are aware of the required secret.
N/A
=> Update 2025-04 release notes with tag event processor api key information

getting-started/templates/AWS/aws_supplemental_values.yml, getting-started/templates/Azure/azure_supplemental_values.yml
Adds the `dynamicformfields` health check annotations to the Azure and AWS ingress controller supplemental values files
Like several other services, dynamicformfields does not use a standard health route (pending readiness probe overhaul) and such it needs to be specified for the ALB to allow routing to the DFF pods. We have supplemental values files for doing this for the Azure and AWS ALBs as starting points.
Supplement only change following standard patterns, no extra testing needed
=> Add DFF health check path to ingress supplementals

getting-started/templates/pilot-sizing.yaml, getting-started/templates/sizing-examples/data-management-sizing-example.yaml
Reduces the DataFrame Service ingestion configuration to make pilot configurations more stable.
The current configuration is not stable. With these values, we've gotten escalations where ingestion requests have failed with `OutOfMemory` exceptions. The default memory request for the DataFrame Service is 4 GB, and the ingestion configuration is tuned to expect 4 GB of memory. The pilot config sets the default memory request to 512 Mi, but we forgot to reduce the ingestion configuration proportionally.
Users may hit issues ingesting large amounts of data, or many tables in parallel, with the adjusted config. That should be a clear indication that they're outside the scale that the pilot …
=> Pilot config: Reduce DataFrame Service ingestion config

getting-started/templates/systemlink-values.yaml
Renames `dataframeservice.ingestion.s3StreamPool.maximumPooledStreams` to `dataframeservice.ingestion.streamPool.maximumPooledStreams` in systemlink-values.yaml.
In 2025-05, the dataframeservice chart had a [breaking change](https://github.com/ni/install-systemlink-enterprise/tree/main/release-notes/2025-05#helm-chart-breaking-changes). Setting the old value leads to a Helm install error.
Ran `helm template` using the updated systemlink-values.yaml.
=> Fix DFS streamPool values in systemlink-values

getting-started/templates/AWS/aws-secrets.yaml, getting-started/templates/AWS/aws_supplemental_values.yml, getting-started/templates/Azure/azure-supplemental-values.yaml, getting-started/templates/Dependencies/MinIO/README.md, getting-started/templates/OnPrem/storage-secrets.yaml, getting-started/templates/OnPrem/storage-values.yaml, getting-started/templates/systemlink-secrets.yaml, getting-started/templates/systemlink-values.yaml
Removes values related to S3 configuration from systemlink-values.yaml and systemlink-secrets.yaml and adds them to AWS/aws_supplemental_values.yml, AWS/aws-secrets.yaml, OnPrem/storage-values.yaml, and OnPrem/storage-secrets.yaml.
I intend to rename aws_supplemental_values.yml to aws-supplemental-values.yaml for consistency in a follow-up PR.
Now that we support Azure Storage, it's confusing to have ATTENTION callouts for S3 in the main values files that aren't relevant when using Azure. Having separate values files to help select between storage backends keeps things organized and easier to reason about.
Ran `helm template` with various combinations of the template files and verified the …
=> Extract S3 values into separate YAML files

getting-started/templates/pilot-sizing.yaml, getting-started/templates/sizing-examples/systems-sizing-example.yaml
Based on the performance testing for tags, we noticed that scaling tags to 2 pods will significantly improve the performance and load the service can handle. 
The default sizing for Tags will fit a larger Tag dataset and the service will have a better performance overall.
Performance testing
=> Udpate default sizing for tags

getting-started/templates/systemlink-secrets.yaml
Fixes an incorrect description in a template file.
Correct customer-facing documentation.
This text is copied directly from the actual Helm chart and conforms to what we are deploying for our internal clusters.
=> Fix incorrect description for webserver.encryptionKey

getting-started/templates/pilot-sizing.yaml, getting-started/templates/sizing-examples/data-management-sizing-example.yaml
Update pilot sizing and example sizing with new Arrow record batch size limit. In theory, only having 2 concurrent requests at a time should allow for 32 MB record batches, even with a 512 MB memory limit, but the Arrow record batches allocate memory from the unmanaged heap. By default, the .NET garbage collector will use up to 75% of available memory. For a 512 MB memory limit, that only leaves 128 MB for the unmanaged heap. This reinforces that there isn't a straightforward formula to follow and that DFS tuning requires testing with representative workflows.
Ensure the pilot sizing is stable when clients are sending data in the Apache Arrow format.
Installed the DFS to minikube using the …
=> Update DFS pilot sizing for Apache Arrow ingestion
